### PR TITLE
update dep version

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
Fix #1

**Comment by ma6254** [comment]
in the Gopkg.lock line 1
```toml
# This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.
```
it's my fault
maybe should add `Gopkg.lock`and`vendor/` to `.gitignore` 
and use `dep ensure` generate it

**Comment by daixiang0** [comment]
`Gopkg.lock` and `vendor` should not be ignored as i saw many go projects do the same.
After update and re-generate lock file, can be solved.

**Comment by ma6254** [comment]
I also know that most projects do this (commit vendor and GoPkg.lock)
but look that

# [dep/FAQ.md](https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory)

## Should I commit my vendor directory?
It's up to you:

### Pros

- It's the only way to get truly reproducible builds, as it guards against upstream renames, deletes and commit history overwrites.
- You don't need an extra dep ensure step to sync vendor/ with Gopkg.lock after most operations, such as go get, cloning, getting latest, merging, etc.

### Cons

- Your repo will be bigger, potentially a lot bigger, though prune can help minimize this problem.
- PR diffs will include changes for files under vendor/ when Gopkg.lock is modified, however files in vendor/ are hidden by default on GitHub.

# https://www.gitignore.io/api/go

```
# Created by https://www.gitignore.io/api/go
# Edit at https://www.gitignore.io/?templates=go

### Go ###
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

### Go Patch ###
/vendor/
/Godeps/

# End of https://www.gitignore.io/api/go
```

**Comment by ma6254** [comment]
Maybe I should abandon godep and embrace gomod

**Comment by daixiang0** [comment]
switch to gomod should be better, godep seems gradually transferred to gomod.

**Comment by daixiang0** [comment]
For now, keep godep work still make sense.

**Pull request closed without merging**
